#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import numpy as np
import matplotlib.pyplot as plt
import time
start_time = time.time()
from scipy.stats import multivariate_normal

################################################################
###################### Calculations ############################
################################################################

for i in range(5):
    print(i)

if (True > 0):
    print("Hello")


N=2
MU, W = np.polynomial.legendre.leggauss(N)

print(MU)
print(W)

###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
