#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import time
start_time = time.time()
import Functions as f

################################################################
######################## Inputs ################################
################################################################

# Constants
Q = 0.01
Sigma_t = 110;Sigma_s=100
# Add adsorption to help converge
if Sigma_t==Sigma_s:
    Sigma_t=Sigma_t*1.0001

# Geometry
L = 10.                       # Width of slab
slices=[10]                   # Number of cuts in slab (looped)
N = 2                         # Number of angle slices
BCs = f.np.zeros(N)           # Zero incoming flux

#Time
T=0                           # total Time (A plot made at T)
dt=1                          # Time steps width
v=1                           # Velocity

MAXITS=10000                  # Max iterations for source iter
loud=False                    # Echo every Iteration?

#Method
Methods=['Iteration:step',
         'Iteration:dd',
         'GMRES:step',]       # Methods to solve with? (looped)

GMRES=False                   # Use GMRES with step discret?

tol=1e-5

################################################################
#################### Initialize Figures ########################
################################################################

Check=0
fig=f.plt.figure(figsize=f.FigureSize)   # Plot all Methods
ax=fig.add_subplot(111)
erfig=f.plt.figure(figsize=f.FigureSize) # Err Plot
erax=erfig.add_subplot(111)              # at T=0

################################################################
##################### Calculations #############################
################################################################

for Scheme in Methods:

    Method=Scheme.split(':')[1]
    #########################################################
    ##################### Set Up ############################
    #########################################################

    for II in slices:
        if Method == 'step': #Step Dude needs one extra
            I=II+1
        elif Method == 'dd':
            I=II
      
        #Width, ang lists for materials
        hx = L/II
        q = f.np.ones(I)*Q
        Sig_t_discr = f.np.ones(I)*Sigma_t
        Sig_s_discr = f.np.ones(I)*Sigma_s
        
        #Initialize psi (for time steps)
        if T==0:
            psi=f.np.zeros((N,I))
            Time=[0]
        else:
            psi=f.np.ones((N,I))*(1/hx)
            Time=f.Timevector(T,dt)

        label_tmp=Scheme+":hx="+str(hx)+",T="
        #########################################################
        #################### Determine phi ######################
        #########################################################

        for t in Time: #Loop over time

            label=label_tmp+str(t)
            
            #Determine phi (new psi is determined for time steps)
            x,phi,it,er,psi=f.solver(I,hx,q,Sig_t_discr,
            Sig_s_discr,N,psi,v,dt,Time,BCs,Scheme,tol,MAXITS,loud)

            #####################################################
            ################ Plot Information ###################
            #####################################################
            fig
            ax,fig=f.plot(x,phi,ax,label,fig,Check)
            #if t==0:
            #    erfig
            #    erax,erfig=f.plotE(it,er,erax,label,erfig,Check)
            Check=Check+1

#########################################################
################### Legend/Save  ########################
#########################################################

fig
f.Legend(ax)
f.plt.savefig('Plots/FluxPlot.pdf')

#erfig
#f.Legend(erax)
#f.plt.savefig('Plots/ErrorPlot.pdf')

###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
